from xml.dom import minidom
from acpc.LattesService import Processar

if __name__ == '__main__':
    processar = Processar(minidom.parse('../files/lattes/curriculo.xml'))
    processar.processar('TRABALHO-EM-EVENTOS', 'DADOS-BASICOS-DO-TRABALHO', 'TITULO-DO-TRABALHO', 'ANO-DO-TRABALHO')
    processar.processar('ARTIGO-PUBLICADO', 'DADOS-BASICOS-DO-ARTIGO', 'TITULO-DO-ARTIGO', 'ANO-DO-ARTIGO')
    processar.processar('LIVRO-PUBLICADO-OU-ORGANIZADO', 'DADOS-BASICOS-DO-LIVRO', 'TITULO-DO-LIVRO')
    processar.processar('CAPITULO-DE-LIVRO-PUBLICADO', 'DADOS-BASICOS-DO-CAPITULO', 'TITULO-DO-CAPITULO-DO-LIVRO')
    processar.processar('TRABALHO-TECNICO', 'DADOS-BASICOS-DO-TRABALHO-TECNICO', 'TITULO-DO-TRABALHO-TECNICO')
    processar.processar('APRESENTACAO-DE-TRABALHO', 'DADOS-BASICOS-DA-APRESENTACAO-DE-TRABALHO')
    processar.processar('CURSO-DE-CURTA-DURACAO-MINISTRADO', 'DADOS-BASICOS-DE-CURSOS-CURTA-DURACAO-MINISTRADO')
    processar.processar('ORGANIZACAO-DE-EVENTO', 'DADOS-BASICOS-DA-ORGANIZACAO-DE-EVENTO')
    processar.processar('OUTRAS-BANCAS-JULGADORAS', 'DADOS-BASICOS-DE-OUTRAS-BANCAS-JULGADORAS')
    processar.processar('PARTICIPACAO-EM-CONGRESSO', 'DADOS-BASICOS-DA-PARTICIPACAO-EM-CONGRESSO', 'TITULO', 'ANO', 'NATUREZA', 'DETALHAMENTO-DA-PARTICIPACAO-EM-CONGRESSO')
    processar.processar('PARTICIPACAO-EM-SEMINARIO', 'DADOS-BASICOS-DA-PARTICIPACAO-EM-SEMINARIO', 'TITULO', 'ANO', 'NATUREZA', 'DETALHAMENTO-DA-PARTICIPACAO-EM-SEMINARIO')
    processar.processar('PARTICIPACAO-EM-SIMPOSIO', 'DADOS-BASICOS-DA-PARTICIPACAO-EM-SIMPOSIO', 'TITULO', 'ANO', 'NATUREZA', 'DETALHAMENTO-DA-PARTICIPACAO-EM-SIMPOSIO')
    processar.processar('PARTICIPACAO-EM-ENCONTRO', 'DADOS-BASICOS-DA-PARTICIPACAO-EM-ENCONTRO', 'TITULO', 'ANO', 'NATUREZA', 'DETALHAMENTO-DA-PARTICIPACAO-EM-ENCONTRO')
    processar.processar('OUTRAS-PARTICIPACOES-EM-EVENTOS-CONGRESSOS', 'DADOS-BASICOS-DE-OUTRAS-PARTICIPACOES-EM-EVENTOS-CONGRESSOS', 'TITULO', 'ANO', 'NATUREZA', 'DETALHAMENTO-DE-OUTRAS-PARTICIPACOES-EM-EVENTOS-CONGRESSOS')
    
    processar.imprimir()
